using System;
using System.Collections.Generic;
using System.Text;

namespace APIVerve
{
    public class CodeDetectorQueryOptions {
public string 0 { get; set; }
public string 1 { get; set; }
public string 2 { get; set; }
public string 3 { get; set; }
public string 4 { get; set; }
public string 5 { get; set; }
public string 6 { get; set; }
public string 7 { get; set; }
public string 8 { get; set; }
public string 9 { get; set; }
public string 10 { get; set; }
public string 11 { get; set; }
public string 12 { get; set; }
public string 13 { get; set; }
public string 14 { get; set; }
public string 15 { get; set; }
public string 16 { get; set; }
public string 17 { get; set; }
public string 18 { get; set; }
public string 19 { get; set; }
public string 20 { get; set; }
public string 21 { get; set; }
public string 22 { get; set; }
public string 23 { get; set; }
public string 24 { get; set; }
public string 25 { get; set; }
public string 26 { get; set; }
public string 27 { get; set; }
public string 28 { get; set; }
public string 29 { get; set; }
public string 30 { get; set; }
public string 31 { get; set; }
public string 32 { get; set; }
public string 33 { get; set; }
public string 34 { get; set; }
public string 35 { get; set; }
public string 36 { get; set; }
public string 37 { get; set; }
public string 38 { get; set; }
public string 39 { get; set; }
public string 40 { get; set; }
public string 41 { get; set; }
public string 42 { get; set; }
public string 43 { get; set; }
public string 44 { get; set; }
public string 45 { get; set; }
public string 46 { get; set; }
public string 47 { get; set; }
public string 48 { get; set; }
public string 49 { get; set; }
public string 50 { get; set; }
public string 51 { get; set; }
public string 52 { get; set; }
public string 53 { get; set; }
public string 54 { get; set; }
public string 55 { get; set; }
public string 56 { get; set; }
public string 57 { get; set; }
public string 58 { get; set; }
public string 59 { get; set; }
public string 60 { get; set; }
public string 61 { get; set; }
public string 62 { get; set; }
public string 63 { get; set; }
public string 64 { get; set; }
public string 65 { get; set; }
public string 66 { get; set; }
public string 67 { get; set; }
public string 68 { get; set; }
public string 69 { get; set; }
public string 70 { get; set; }
public string 71 { get; set; }
public string 72 { get; set; }
public string 73 { get; set; }
public string 74 { get; set; }
public string 75 { get; set; }
public string 76 { get; set; }
public string 77 { get; set; }
public string 78 { get; set; }
public string 79 { get; set; }
public string 80 { get; set; }
public string 81 { get; set; }
public string 82 { get; set; }
public string 83 { get; set; }
public string 84 { get; set; }
public string 85 { get; set; }
public string 86 { get; set; }
public string 87 { get; set; }
public string 88 { get; set; }
public string 89 { get; set; }
public string 90 { get; set; }
public string 91 { get; set; }
public string 92 { get; set; }
public string 93 { get; set; }
public string 94 { get; set; }
public string 95 { get; set; }
public string 96 { get; set; }
public string 97 { get; set; }
public string 98 { get; set; }
public string 99 { get; set; }
public string 100 { get; set; }
public string 101 { get; set; }
public string 102 { get; set; }
public string 103 { get; set; }
public string 104 { get; set; }
public string 105 { get; set; }
public string 106 { get; set; }
public string 107 { get; set; }
public string 108 { get; set; }
public string 109 { get; set; }
public string 110 { get; set; }
public string 111 { get; set; }
public string 112 { get; set; }
public string 113 { get; set; }
public string 114 { get; set; }
public string 115 { get; set; }
public string 116 { get; set; }
public string 117 { get; set; }
public string 118 { get; set; }
public string 119 { get; set; }
public string 120 { get; set; }
public string 121 { get; set; }
public string 122 { get; set; }
public string 123 { get; set; }
public string 124 { get; set; }
public string 125 { get; set; }
public string 126 { get; set; }
public string 127 { get; set; }
public string 128 { get; set; }
public string 129 { get; set; }
public string 130 { get; set; }
public string 131 { get; set; }
public string 132 { get; set; }
public string 133 { get; set; }
public string 134 { get; set; }
public string 135 { get; set; }
public string 136 { get; set; }
public string 137 { get; set; }
public string 138 { get; set; }
public string 139 { get; set; }
public string 140 { get; set; }
public string 141 { get; set; }
public string 142 { get; set; }
public string 143 { get; set; }
public string 144 { get; set; }
public string 145 { get; set; }
public string 146 { get; set; }
public string 147 { get; set; }
public string 148 { get; set; }
public string 149 { get; set; }
public string 150 { get; set; }
public string 151 { get; set; }
public string 152 { get; set; }
public string 153 { get; set; }
public string 154 { get; set; }
public string 155 { get; set; }
public string 156 { get; set; }
public string 157 { get; set; }
public string 158 { get; set; }
public string 159 { get; set; }
public string 160 { get; set; }
public string 161 { get; set; }
public string 162 { get; set; }
public string 163 { get; set; }
public string 164 { get; set; }
public string 165 { get; set; }
public string 166 { get; set; }
public string 167 { get; set; }
public string 168 { get; set; }
public string 169 { get; set; }
public string 170 { get; set; }
public string 171 { get; set; }
public string 172 { get; set; }
public string 173 { get; set; }
public string 174 { get; set; }
public string 175 { get; set; }
public string 176 { get; set; }
public string 177 { get; set; }
public string 178 { get; set; }
public string 179 { get; set; }
public string 180 { get; set; }
public string 181 { get; set; }
public string 182 { get; set; }
public string 183 { get; set; }
public string 184 { get; set; }
public string 185 { get; set; }
public string 186 { get; set; }
public string 187 { get; set; }
public string 188 { get; set; }
public string 189 { get; set; }
public string 190 { get; set; }
public string 191 { get; set; }
public string 192 { get; set; }
public string 193 { get; set; }
public string 194 { get; set; }
public string 195 { get; set; }
public string 196 { get; set; }
public string 197 { get; set; }
public string 198 { get; set; }
public string 199 { get; set; }
public string 200 { get; set; }
public string 201 { get; set; }
public string 202 { get; set; }
public string 203 { get; set; }
public string 204 { get; set; }
public string 205 { get; set; }
public string 206 { get; set; }
public string 207 { get; set; }
public string 208 { get; set; }
public string 209 { get; set; }
public string 210 { get; set; }
public string 211 { get; set; }
public string 212 { get; set; }
public string 213 { get; set; }
public string 214 { get; set; }
public string 215 { get; set; }
public string 216 { get; set; }
public string 217 { get; set; }
public string 218 { get; set; }
public string 219 { get; set; }
public string 220 { get; set; }
public string 221 { get; set; }
public string 222 { get; set; }
public string 223 { get; set; }
public string 224 { get; set; }
public string 225 { get; set; }
public string 226 { get; set; }
public string 227 { get; set; }
public string 228 { get; set; }
public string 229 { get; set; }
public string 230 { get; set; }
public string 231 { get; set; }
public string 232 { get; set; }
public string 233 { get; set; }
public string 234 { get; set; }
public string 235 { get; set; }
public string 236 { get; set; }
public string 237 { get; set; }
public string 238 { get; set; }
public string 239 { get; set; }
public string 240 { get; set; }
public string 241 { get; set; }
public string 242 { get; set; }
public string 243 { get; set; }
public string 244 { get; set; }
public string 245 { get; set; }
public string 246 { get; set; }
public string 247 { get; set; }
public string 248 { get; set; }
public string 249 { get; set; }
public string 250 { get; set; }
public string 251 { get; set; }
public string 252 { get; set; }
public string 253 { get; set; }
public string 254 { get; set; }
public string 255 { get; set; }
public string 256 { get; set; }
public string 257 { get; set; }
public string 258 { get; set; }
public string 259 { get; set; }
public string 260 { get; set; }
public string 261 { get; set; }
public string 262 { get; set; }
public string 263 { get; set; }
public string 264 { get; set; }
public string 265 { get; set; }
public string 266 { get; set; }
public string 267 { get; set; }
public string 268 { get; set; }
public string 269 { get; set; }
public string 270 { get; set; }
public string 271 { get; set; }
public string 272 { get; set; }
public string 273 { get; set; }
public string 274 { get; set; }
public string 275 { get; set; }
public string 276 { get; set; }
public string 277 { get; set; }
public string 278 { get; set; }
public string 279 { get; set; }
public string 280 { get; set; }
public string 281 { get; set; }
public string 282 { get; set; }
public string 283 { get; set; }
public string 284 { get; set; }
public string 285 { get; set; }
public string 286 { get; set; }
public string 287 { get; set; }
public string 288 { get; set; }
public string 289 { get; set; }
public string 290 { get; set; }
public string 291 { get; set; }
public string 292 { get; set; }
public string 293 { get; set; }
public string 294 { get; set; }
public string 295 { get; set; }
public string 296 { get; set; }
public string 297 { get; set; }
public string 298 { get; set; }
public string 299 { get; set; }
public string 300 { get; set; }
public string 301 { get; set; }
public string 302 { get; set; }
public string 303 { get; set; }
public string 304 { get; set; }
public string 305 { get; set; }
public string 306 { get; set; }
public string 307 { get; set; }
public string 308 { get; set; }
public string 309 { get; set; }
public string 310 { get; set; }
public string 311 { get; set; }
public string 312 { get; set; }
public string 313 { get; set; }
public string 314 { get; set; }
public string 315 { get; set; }
public string 316 { get; set; }
public string 317 { get; set; }
public string 318 { get; set; }
public string 319 { get; set; }
public string 320 { get; set; }
public string 321 { get; set; }
public string 322 { get; set; }
public string 323 { get; set; }
public string 324 { get; set; }
public string 325 { get; set; }
public string 326 { get; set; }
public string 327 { get; set; }
public string 328 { get; set; }
public string 329 { get; set; }
public string 330 { get; set; }
public string 331 { get; set; }
public string 332 { get; set; }
public string 333 { get; set; }
public string 334 { get; set; }
public string 335 { get; set; }
public string 336 { get; set; }
public string 337 { get; set; }
public string 338 { get; set; }
public string 339 { get; set; }
public string 340 { get; set; }
public string 341 { get; set; }
public string 342 { get; set; }
public string 343 { get; set; }
public string 344 { get; set; }
public string 345 { get; set; }
public string 346 { get; set; }
public string 347 { get; set; }
}
}
